from pydantic import BaseModel, Field
from datetime import datetime


class DTOBSheets(BaseModel):
    fecha_registro: str|None = Field(alias='Marca temporal')
    nombre: str|None = Field(alias='Inserta tu nombre de usuario de facebook')
    telefono: int|None = Field(alias='Ingresa tu número de celular (sin espacios)')
    tipo_pedido: str|None = Field(alias='¿Qué pedirás?')
    color_mandil_kit: str|None = Field(alias='Color del mandil - Kit ', default=None)
    talla_guantes_kit: str|None = Field(alias='Tamaño de guantes (hule y nitrilo) - Kit', default=None)
    numero_kits: int|None = Field(alias='Número de kits.', default=0)
    colm_combo_amarillo_mango: int|str|None = Field(alias='Color de mandiles - Cowmpadres [Amarillo mango]', default=0)
    colm_combo_rojo: int|str|None = Field(alias='Color de mandiles - Cowmpadres [Rojo]', default=0)
    colm_combo_vino: int|str|None = Field(alias='Color de mandiles - Cowmpadres [Vino]', default=0)
    colm_combo_blanco: int|str|None = Field(alias='Color de mandiles - Cowmpadres [Blanco]', default=0)
    colm_combo_negro: int|str|None = Field(alias='Color de mandiles - Cowmpadres [Negro]', default=0)
    colm_combo_azul_pastel: int|str|None = Field(alias='Color de mandiles - Cowmpadres [Azul pastel]', default=0)
    colm_combo_azul_rey: int|str|None = Field(alias='Color de mandiles - Cowmpadres [Azul rey]', default=0)
    colm_combo_azul_marino: int|str|None = Field(alias='Color de mandiles - Cowmpadres [Azul marino]', default=0)
    colm_combo_morado: int|str|None = Field(alias='Color de mandiles - Cowmpadres [Morado]', default=0)
    colm_combo_lila: int|str|None = Field(alias='Color de mandiles - Cowmpadres [Lila]',default=0)
    colm_combo_turquesa: int|str|None = Field(alias='Color de mandiles - Cowmpadres [Turquesa]', default=0)
    colm_combo_rosa_pastel: int|str|None = Field(alias='Color de mandiles - Cowmpadres [Rosa pastel]', default=0)
    colm_combo_rosa_barbie: int|str|None = Field(alias='Color de mandiles - Cowmpadres [Rosa barbie]', default=0)
    colm_combo_verde_bandera: int|str|None = Field(alias='Color de mandiles - Cowmpadres [Verde bandera]', default=0)
    colm_combo_verde_militar: int|str|None = Field(alias='Color de mandiles - Cowmpadres [Verde militar]', default=0)
    combo_talla_guantesp_chicos: int|str|None = Field(alias='Talla de guantes de plástico - Cowmpadres [Chicos]', default=0)
    combo_talla_guantesp_medianos: int|str|None = Field(alias='Talla de guantes de plástico - Cowmpadres [Medianos]', default=0)
    combo_talla_guantesp_grandes: int|str|None = Field(alias='Talla de guantes de plástico - Cowmpadres [Grandes]', default=0)
    pregunta_kit_extra: str|None = Field(alias='¿Quieres agregar un kit extra?', default=None)
    col_kit_extra: str|None = Field(alias='Color del mandil - Kextra', default=None)
    talla_guantes_kit_extra: str|None = Field(alias='Tamaño de guantes (hule y nitrilo) - Kextra', default=None)
    pregunta_pz_extra: str|None = Field(alias='¿Quieres agregar piezas sueltas (extras)?', default=None)
    colm_pz_amarillo_mango: int|str|None = Field(alias='Mandil (color) - Pieza [Amarillo mango]', default=0)
    colm_pz_rojo: int|str|None = Field(alias='Mandil (color) - Pieza [Rojo]', default=0)
    colm_pz_vino: int|str|None = Field(alias='Mandil (color) - Pieza [Vino]', default=0)
    colm_pz_blanco: int|str|None = Field(alias='Mandil (color) - Pieza [Blanco]', default=0)
    colm_pz_negro: int|str|None = Field(alias='Mandil (color) - Pieza [Negro]', default=0)
    colm_pz_azul_pastel: int|str|None = Field(alias='Mandil (color) - Pieza [Azul pastel]', default=0)
    colm_pz_azul_rey: int|str|None = Field(alias='Mandil (color) - Pieza [Azul rey]', default=0)
    colm_pz_azul_marino: int|str|None = Field(alias='Mandil (color) - Pieza [Azul marino]', default=0)
    colm_pz_morado: int|str|None = Field(alias='Mandil (color) - Pieza [Morado]', default=0)
    colm_pz_lila: int|str|None = Field(alias='Mandil (color) - Pieza [Lila]', default=0)
    colm_pz_turquesa: int|str|None = Field(alias='Mandil (color) - Pieza [Turquesa]', default=0)
    colm_pz_rosa_pastel: int|str|None = Field(alias='Mandil (color) - Pieza [Rosa pastel]', default=0)
    colm_pz_rosa_barbie: int|str|None = Field(alias='Mandil (color) - Pieza [Rosa barbie]', default=0)
    colm_pz_verde_bandera: int|str|None = Field(alias='Mandil (color) - Pieza [Verde bandera]', default=0)
    colm_pz_verde_militar: int|str|None = Field(alias='Mandil (color) - Pieza [Verde militar]', default=0)
    pz_talla_guantesp_chicos: int|str|None = Field(alias='Guantes de plástico (talla) - Pieza [Chicos]', default=0)
    pz_talla_guantesp_medianos: int|str|None = Field(alias='Guantes de plástico (talla) - Pieza [Medianos]', default=0)
    pz_talla_guantesp_grandes: int|str|None = Field(alias='Guantes de plástico (talla) - Pieza [Grandes]', default=0)
    pz_talla_guantesn_chicos: int|str|None = Field(alias='Guantes de nitrilo (talla) - Pieza [Chicos]', default=0)
    pz_talla_guantesn_medianos: int|str|None = Field(alias='Guantes de nitrilo (talla) - Pieza [Medianos]', default=0)
    pz_talla_guantesn_grandes: int|str|None = Field(alias='Guantes de nitrilo (talla) - Pieza [Grandes]', default=0)
    pz_cuchillos: int|str|None = Field(alias='Cuchillos - Pieza', default=0)
    especial_bolsa_tote: int|None = Field(alias='Tote bag - Especial', default=0)
    extra_bolsa_tote: str|None = Field(alias='¿Quieres recibir tu pedido en una tote bag?', default=None)
    fecha_entrega: str|None = Field(alias='Fechas', default=None)